### ISSUE TITLE
Protocol for sds update

### ISSUE THREAD

**Issue by jjmcnelis** [aria-jpl/standard_product#11]
Seeing evidence that config files were overwritten with recent sds deployments. Document protocol for sds update to preserve config files on factotum/mozart/etc.

**Comment by riverma** [comment]
@marjo-luc - could you work with @hookhua / HySDS team to identify & propose the more permanent solution to this issue?

**Comment by marjo-luc** [comment]
The only configurations that are at risk of being overwritten are those that exist only on factotum. Whenever the cluster is updated, restarted, etc, the configurations defined on mozart are shipped to factotum. To avoid configurations from being overwritten, follow the steps defined here after making changes to the configuration files from the mozart host: https://hysds-core.atlassian.net/wiki/spaces/HYS/pages/521371658/Start+Stop+Restart+Status+Reset+Supervisord

It would also be prudent to commit the adaptation-specific configurations to a private repo, as I believe we intend to do. This would help us maintain a history of changes and allow us to pull our configurations when we make updates to new versions of hysds core.
